config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'clients/registrations'}
  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root
    end
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  get '/init_app', to: "home#init_app"
  resources :trucks
  resources :stretches
  resources :orders
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/stretch.rb
class Stretch < ApplicationRecord
  belongs_to :route
  belongs_to :truck
end

app/controllers/stretches_controller.rb
class StretchesController < ApplicationController
  before_action :set_stretch, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[ index show new create edit update destroy]

  # GET /stretches or /stretches.json
  def index
    @stretches = Stretch.where(truck_id: current_user.truck)
  end

  # GET /stretches/1 or /stretches/1.json
  def show
  end

  # GET /stretches/new
  def new
    @stretch = Stretch.new
  end

  # GET /stretches/1/edit
  def edit
  end

  # POST /stretches or /stretches.json
  def create
    @stretch = Stretch.new(stretch_params)

    respond_to do |format|
      if @stretch.save
        format.html { redirect_to @stretch, notice: "Stretch was successfully created." }
        format.json { render :show, status: :created, location: @stretch }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @stretch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stretches/1 or /stretches/1.json
  def update
    respond_to do |format|
      if @stretch.update(stretch_params)
        format.html { redirect_to @stretch, notice: "Stretch was successfully updated." }
        format.json { render :show, status: :ok, location: @stretch }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @stretch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stretches/1 or /stretches/1.json
  def destroy
    @stretch.destroy
    respond_to do |format|
      format.html { redirect_to stretches_url, notice: "Stretch was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stretch
      @stretch = Stretch.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def stretch_params
      params.require(:stretch).permit(:start_datetime, :end_datetime, :start_place_lat, :start_place_lon, :end_place_lat, :end_place_lon, :route_id)
    end
end

app/helpers/stretches_helper.rb
module StretchesHelper
end

app/views/stretches/_form.html.erb
<%= form_with(model: stretch, local: true) do |form| %>
  <% if stretch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stretch.errors.count, "error") %> prohibited this stretch from being saved:</h2>

      <ul>
      <% stretch.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :start_datetime %>
    <%= form.datetime_select :start_datetime %>
  </div>

  <div class="field">
    <%= form.label :end_datetime %>
    <%= form.datetime_select :end_datetime %>
  </div>

  <div class="field">
    <%= form.label :start_place_lat %>
    <%= form.text_field :start_place_lat %>
  </div>

  <div class="field">
    <%= form.label :start_place_lon %>
    <%= form.text_field :start_place_lon %>
  </div>

  <div class="field">
    <%= form.label :end_place_lat %>
    <%= form.text_field :end_place_lat %>
  </div>

  <div class="field">
    <%= form.label :end_place_lon %>
    <%= form.text_field :end_place_lon %>
  </div>

  <div class="field">
    <%= form.label :route_id %>
    <%= form.text_field :route_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stretches/edit.html.erb
<h1>Editing Stretch</h1>

<%= render 'form', stretch: @stretch %>

<%= link_to 'Show', @stretch %> |
<%= link_to 'Back', stretches_path %>

app/views/stretches/index.html.erb
<h1 class="title">Przypisane do ciebie odcinki</h1>

<table class="table is-striped" style="margin: auto">
  <thead>
    <tr>
      <th>Czas startowy</th>
      <th>Czas końcowy</th>
      <th>Punkt początkowy</th>
      <th>Punkt końcowy</th>
      <th>Waga Towaru</th>
      <th>Imie klienta</th>
      <th>Nazwisko klienta</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stretches.each do |stretch| %>
      <tr>
        <td><%= stretch.start_datetime.strftime('%d/%m/%Y %H:%M') %></td>
        <td><%= stretch.end_datetime.strftime('%d/%m/%Y %H:%M') %></td>
        <td><%= "(#{stretch.start_place_lat}, #{stretch.start_place_lon})"%></td>
        <td><%= "(#{stretch.end_place_lat}, #{stretch.end_place_lon})"%></td>
        <td><%= stretch.route.order.payload_weight%></td>
        <td><%= stretch.route.order.user.name %></td>
        <td><%= stretch.route.order.user.surname %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/stretches/new.html.erb
<h1>New Stretch</h1>

<%= render 'form', stretch: @stretch %>

<%= link_to 'Back', stretches_path %>

app/views/stretches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start datetime:</strong>
  <%= @stretch.start_datetime %>
</p>

<p>
  <strong>End datetime:</strong>
  <%= @stretch.end_datetime %>
</p>

<p>
  <strong>Start place lat:</strong>
  <%= @stretch.start_place_lat %>
</p>

<p>
  <strong>Start place lon:</strong>
  <%= @stretch.start_place_lon %>
</p>

<p>
  <strong>End place lat:</strong>
  <%= @stretch.end_place_lat %>
</p>

<p>
  <strong>End place lon:</strong>
  <%= @stretch.end_place_lon %>
</p>

<p>
  <strong>Route:</strong>
  <%= @stretch.route %>
</p>

<%= link_to 'Edit', edit_stretch_path(@stretch) %> |
<%= link_to 'Back', stretches_path %>