config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'clients/registrations'}
  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root
    end
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  get '/init_app', to: "home#init_app"
  resources :trucks
  resources :stretches
  resources :orders
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/truck.rb
class Truck < ApplicationRecord
  has_many :stretches
  belongs_to :user
end

app/controllers/trucks_controller.rb
class TrucksController < ApplicationController
  before_action :set_truck, only: %i[ show edit update destroy ]

  # GET /trucks or /trucks.json
  def index
    @trucks = Truck.all
  end

  # GET /trucks/1 or /trucks/1.json
  def show
  end

  # GET /trucks/new
  def new
    @truck = Truck.new
  end

  # GET /trucks/1/edit
  def edit
  end

  # POST /trucks or /trucks.json
  def create
    @truck = Truck.new(truck_params)

    respond_to do |format|
      if @truck.save
        format.html { redirect_to @truck, notice: "Truck was successfully created." }
        format.json { render :show, status: :created, location: @truck }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @truck.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trucks/1 or /trucks/1.json
  def update
    respond_to do |format|
      if @truck.update(truck_params)
        format.html { redirect_to @truck, notice: "Truck was successfully updated." }
        format.json { render :show, status: :ok, location: @truck }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @truck.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trucks/1 or /trucks/1.json
  def destroy
    @truck.destroy
    respond_to do |format|
      format.html { redirect_to trucks_url, notice: "Truck was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_truck
      @truck = Truck.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def truck_params
      params.require(:truck).permit(:height, :capacity, :position_lat, :position_lon, :user_id)
    end
end

app/helpers/trucks_helper.rb
module TrucksHelper
end

app/views/trucks/_form.html.erb
<%= form_with(model: truck, local: true) do |form| %>
  <% if truck.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(truck.errors.count, "error") %> prohibited this truck from being saved:</h2>

      <ul>
      <% truck.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :height %>
    <%= form.text_field :height %>
  </div>

  <div class="field">
    <%= form.label :capacity %>
    <%= form.text_field :capacity %>
  </div>

  <div class="field">
    <%= form.label :position_lat %>
    <%= form.text_field :position_lat %>
  </div>

  <div class="field">
    <%= form.label :position_lon %>
    <%= form.text_field :position_lon %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/trucks/edit.html.erb
<h1>Editing Truck</h1>

<%= render 'form', truck: @truck %>

<%= link_to 'Show', @truck %> |
<%= link_to 'Back', trucks_path %>

app/views/trucks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trucks</h1>

<table>
  <thead>
    <tr>
      <th>Height</th>
      <th>Capacity</th>
      <th>Position lat</th>
      <th>Position lon</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trucks.each do |truck| %>
      <tr>
        <td><%= truck.height %></td>
        <td><%= truck.capacity %></td>
        <td><%= truck.position_lat %></td>
        <td><%= truck.position_lon %></td>
        <td><%= link_to 'Show', truck %></td>
        <td><%= link_to 'Edit', edit_truck_path(truck) %></td>
        <td><%= link_to 'Destroy', truck, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Truck', new_truck_path %>

app/views/trucks/new.html.erb
<h1>New Truck</h1>

<%= render 'form', truck: @truck %>

<%= link_to 'Back', trucks_path %>

app/views/trucks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Height:</strong>
  <%= @truck.height %>
</p>

<p>
  <strong>Capacity:</strong>
  <%= @truck.capacity %>
</p>

<p>
  <strong>Position lat:</strong>
  <%= @truck.position_lat %>
</p>

<p>
  <strong>Position lon:</strong>
  <%= @truck.position_lon %>
</p>

<%= link_to 'Edit', edit_truck_path(@truck) %> |
<%= link_to 'Back', trucks_path %>